spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://krushna:krushna@localhost:27017/chat_nexus?authSource=admin}

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}
